name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    services:
      db:
        image: postgres:14.4-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: typegraphql-prisma
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup project
        run: |
          npm install

      - name: Check codebase
        run: |
          npm run check:format
          npm run check:type

      - name: Run tests
        run: |
          npm run test:ci
        env:
          CI: true
          TEST_DATABASE_URL: postgresql://user:password@localhost:5432/typegraphql-prisma
